# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.cache/wt [current_project]
set_property parent.project_path D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/vivado/Project/SingleCycleCPU/SingleCycleCPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/ALU.v
  D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Control_Unit.v
  D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Data_memory.v
  D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Debounce.v
  D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Extension.v
  D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Ins_memory.v
  D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/MUX_32b.v
  D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/MUX_5b.v
  D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Program_counter.v
  D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Register_File.v
  D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/SegLed.v
  D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Single_Cycle_CPU.v
  D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Basys3.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/constrs_1/new/Single_Cycle_CPU.xdc
set_property used_in_implementation false [get_files D:/vivado/Project/SingleCycleCPU/SingleCycleCPU.srcs/constrs_1/new/Single_Cycle_CPU.xdc]


synth_design -top Basys3 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Basys3.dcp

catch { report_utilization -file Basys3_utilization_synth.rpt -pb Basys3_utilization_synth.pb }
